/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ConferenceRouteImport } from './routes/conference'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as MediaRouteImport } from './routes/media'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as TeacherAuthRouteImport } from './routes/teacher-auth'
import { Route as TeacherDashboardRouteImport } from './routes/teacher-dashboard'
import { Route as TeacherSignupRouteImport } from './routes/teacher-signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThankYouRouteImport } from './routes/thank-you'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferenceRoute = ConferenceRouteImport.update({
  id: '/conference',
  path: '/conference',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAuthRoute = TeacherAuthRouteImport.update({
  id: '/teacher-auth',
  path: '/teacher-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/teacher-dashboard',
  path: '/teacher-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSignupRoute = TeacherSignupRouteImport.update({
  id: '/teacher-signup',
  path: '/teacher-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/compliance': typeof ComplianceRoute
  '/conference': typeof ConferenceRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/media': typeof MediaRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/teacher': typeof TeacherRoute
  '/teacher-auth': typeof TeacherAuthRoute
  '/teacher-dashboard': typeof TeacherDashboardRoute
  '/teacher-signup': typeof TeacherSignupRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/compliance': typeof ComplianceRoute
  '/conference': typeof ConferenceRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/media': typeof MediaRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/teacher': typeof TeacherRoute
  '/teacher-auth': typeof TeacherAuthRoute
  '/teacher-dashboard': typeof TeacherDashboardRoute
  '/teacher-signup': typeof TeacherSignupRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/compliance': typeof ComplianceRoute
  '/conference': typeof ConferenceRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/media': typeof MediaRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/teacher': typeof TeacherRoute
  '/teacher-auth': typeof TeacherAuthRoute
  '/teacher-dashboard': typeof TeacherDashboardRoute
  '/teacher-signup': typeof TeacherSignupRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/compliance'
    | '/conference'
    | '/contact'
    | '/dashboard'
    | '/demo'
    | '/faq'
    | '/features'
    | '/media'
    | '/privacy'
    | '/reset-password'
    | '/teacher'
    | '/teacher-auth'
    | '/teacher-dashboard'
    | '/teacher-signup'
    | '/terms'
    | '/thank-you'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/compliance'
    | '/conference'
    | '/contact'
    | '/dashboard'
    | '/demo'
    | '/faq'
    | '/features'
    | '/media'
    | '/privacy'
    | '/reset-password'
    | '/teacher'
    | '/teacher-auth'
    | '/teacher-dashboard'
    | '/teacher-signup'
    | '/terms'
    | '/thank-you'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/compliance'
    | '/conference'
    | '/contact'
    | '/dashboard'
    | '/demo'
    | '/faq'
    | '/features'
    | '/media'
    | '/privacy'
    | '/reset-password'
    | '/teacher'
    | '/teacher-auth'
    | '/teacher-dashboard'
    | '/teacher-signup'
    | '/terms'
    | '/thank-you'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ComplianceRoute: typeof ComplianceRoute
  ConferenceRoute: typeof ConferenceRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  MediaRoute: typeof MediaRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TeacherRoute: typeof TeacherRoute
  TeacherAuthRoute: typeof TeacherAuthRoute
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherSignupRoute: typeof TeacherSignupRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conference': {
      id: '/conference'
      path: '/conference'
      fullPath: '/conference'
      preLoaderRoute: typeof ConferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-auth': {
      id: '/teacher-auth'
      path: '/teacher-auth'
      fullPath: '/teacher-auth'
      preLoaderRoute: typeof TeacherAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-dashboard': {
      id: '/teacher-dashboard'
      path: '/teacher-dashboard'
      fullPath: '/teacher-dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-signup': {
      id: '/teacher-signup'
      path: '/teacher-signup'
      fullPath: '/teacher-signup'
      preLoaderRoute: typeof TeacherSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ComplianceRoute: ComplianceRoute,
  ConferenceRoute: ConferenceRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  MediaRoute: MediaRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TeacherRoute: TeacherRoute,
  TeacherAuthRoute: TeacherAuthRoute,
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherSignupRoute: TeacherSignupRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
